In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.tensor as tensor
torch.manual_seed(1)
import torch.utils.data

In [5]:
lstm = nn.LSTM(3, 3)

In [6]:
inputs = [torch.randn(1, 3) for _ in range(5)]
print(inputs)

[tensor([[-1.8313,  0.6272,  1.0935]]), tensor([[ 0.0939,  1.2381, -1.3459]]), tensor([[ 0.5119, -0.6933, -0.1668]]), tensor([[-0.9999, -1.6476,  0.8098]]), tensor([[ 0.0554,  1.1340, -0.5326]])]


In [7]:
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
print(hidden)

(tensor([[[ 0.6592, -1.5964, -0.3769]]]), tensor([[[-3.1020, -0.0995, -0.7213]]]))


In [9]:
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    print(i)
    out, hidden = lstm(i.view(1, 1, -1), hidden)

tensor([[-1.8313,  0.6272,  1.0935]])
tensor([[ 0.0939,  1.2381, -1.3459]])
tensor([[ 0.5119, -0.6933, -0.1668]])
tensor([[-0.9999, -1.6476,  0.8098]])
tensor([[ 0.0554,  1.1340, -0.5326]])


In [41]:
a = torch.LongTensor([[1,3],[2,4],[5,7],[6,8]])

In [42]:
a.permute(1,0).view(2,2,2)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

In [44]:
a.view(-1)

tensor([1, 3, 2, 4, 5, 7, 6, 8])

In [51]:
idx = torch.randperm(a.size()[1])
idx

tensor([4, 0])

In [46]:
a.view(-1)[idx].view(a.size())

tensor([[7, 6],
        [5, 2],
        [8, 1],
        [4, 3]])

In [96]:
a = torch.LongTensor([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]],[[17,18],[19,20],[21,22],[23,24]]])

In [97]:
a

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]])

In [102]:
ix = torch.randperm(a.size()[1])
a[]

tensor([0, 3, 2, 1])

In [82]:
dataset = torch.utils.data.TensorDataset(b)

In [83]:
loader = torch.utils.data.DataLoader(dataset, batch_size=3, shuffle=True)

In [84]:
loader

In [85]:
for batch in loader:
    print(batch)

[tensor([[[ 1,  2],
         [ 9, 10],
         [17, 18]],

        [[ 3,  4],
         [11, 12],
         [19, 20]],

        [[ 7,  8],
         [15, 16],
         [23, 24]],

        [[ 5,  6],
         [13, 14],
         [21, 22]]])]


In [92]:
a = torch.LongTensor([[1,2],[3,4]])
b = torch.LongTensor([[1,2],[3,4]])
print(a.size())
print(b.size())

torch.Size([2, 2])
torch.Size([2, 2])


In [93]:
torch.stack([a,b]).size()

torch.Size([2, 2, 2])